/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

Ext.define('Flamingo.view.workflowdesigner.nodeList.NodeListModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.nodeListModel',

    stores: {
        nodemeta: {
            model: 'Flamingo.model.workflowdesigner.NodeMeta',

            data: [ // TODO description 다국어 처리
                {
                    "type": "OTHERS",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-condition-if.png",
                    "identifier": "BPMN_INCLUSIVE_FORK",
                    "name": 'Conditional branch',
                    "qualifierLabel": "inclusive_fork",
                    "description": 'Conditional branch',
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 1,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 1,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "END",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "OTHERS",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-condition-end.png",
                    "identifier": "BPMN_INCLUSIVE_JOIN",
                    "name": 'Exit conditions',
                    "qualifierLabel": "inclusive_join",
                    "description": 'Exit conditions',
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 1,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 1,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "END",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "OTHERS",
                    "icon": CONSTANTS.CONTEXT_PATH + '/resources/images/icons/workflow/workflow-pararell-process.png',
                    "identifier": "BPMN_PARALLEL",
                    "name": 'Parallelism',
                    "qualifierLabel": "parallel",
                    "description": 'Parallelism',
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "OTHERS",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-pararell-end.png",
                    "identifier": "BPMN_JOIN",
                    "name": 'Parallel Exit',
                    "qualifierLabel": "join",
                    "description": 'Parallel Exit',
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 1,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 1,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "END",
                    "notAllowedNextNodes": ""
                },
                /*
                 {
                 "type": "OTHERS",
                 "icon": CONSTANTS.CONTEXT_PATH + '/resources/images/icons/workflow/workflow-sub.png',
                 "identifier": "SUBPROCESS",
                 "name": message.msg('workflow.common.subflow'),
                 "qualifierLabel": "subprocess",
                 "description": message.msg('workflow.common.subflow'),
                 "isCheckColumns": false,
                 "fixedInputColumns": false,
                 "fixedOutputColumns": false,
                 "readOnlyOutputColumns": false,
                 "ignoreInput": true,
                 "ignoreOutput": true,
                 "minPrevNodeCounts": 0,
                 "maxPrevNodeCounts": -1,
                 "minNextNodeCounts": 0,
                 "maxNextNodeCounts": -1,
                 "notAllowedPrevTypes": "",
                 "notAllowedNextTypes": "",
                 "notAllowedPrevNodes": "",
                 "notAllowedNextNodes": ""
                 },
                 */
                {
                    "type": "HADOOP",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mapreduce.png",
                    "identifier": "HADOOP_MR",
                    "name": 'MapReduce',
                    "qualifierLabel": "mr",
                    "description": 'MapReduce',
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "HADOOP",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-pig.png",
                    "identifier": "HADOOP_PIG",
                    "name": 'Pig Latin Script',
                    "qualifierLabel": "pig",
                    "description": 'Pig Latin Script',
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 1,
                    "maxPrevNodeCounts": 1,
                    "minNextNodeCounts": 1,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "HADOOP",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-hive.png",
                    "identifier": "HADOOP_HIVE",
                    "name": 'Hive Query',
                    "qualifierLabel": "hive",
                    "description": 'Hive Query',
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 1,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 1,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "INMEMORY",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-spark.png",
                    "identifier": "HADOOP_SPARK",
                    "name": 'Spark',
                    "qualifierLabel": "mr",
                    "description": 'Spark',
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },                
                {
                    "type": "INMEMORY",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-spark.png",
                    "identifier": "HADOOP_SPARK_LINEAR_REGRESSION",
                    "name": "Spark Linear Regression",
                    "qualifierLabel": "lrl",
                    "description": "Spark Linear Regression",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "HADOOP",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-java.png",
                    "identifier": "HADOOP_JAVA",
                    "name": 'Java',
                    "qualifierLabel": "java",
                    "description": 'Java',
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 1,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 1,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "HADOOP",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-java.png",
                    "identifier": "HADOOP_SQOOP_IMPORT",
                    "name": 'Sqoop Import',
                    "qualifierLabel": "si",
                    "description": 'Sqoop Import',
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 1,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 1,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "HADOOP",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-java.png",
//                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-export.png",
                    "identifier": "HADOOP_SQOOP_EXPORT",
                    "name": 'Sqoop Export',
                    "qualifierLabel": "so",
                    "description": 'Sqoop Export',
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 1,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "OTHERS",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-shell.png",
                    "identifier": "HADOOP_SHELL",
                    "name": 'Shell Script',
                    "qualifierLabel": "shell",
                    "description": 'Shell Script',
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 1,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 1,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "OTHERS",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-r.png",
                    "identifier": "HADOOP_R",
                    "name": 'R Script',
                    "qualifierLabel": "R",
                    "description": 'R Script',
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 1,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 1,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "OTHERS",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-python.png",
                    "identifier": "HADOOP_PYTHON",
                    "name": 'Python Script',
                    "qualifierLabel": "python",
                    "description": 'Python Script',
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 1,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 1,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "STATISTICS",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-statistics.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_ANKUS_NUMERIC_STATISTICS",
                    "name": "Numeric Statistics Distribution",
                    "qualifierLabel": "anumstat",
                    "description": "Numeric Statistics Distribution",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "STATISTICS",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-statistics.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_ANKUS_NOMINAL_STATISTICS",
                    "name": "Nominal Statistics Distribution",
                    "qualifierLabel": "nominal",
                    "description": "Nominal Statistics Distribution",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "STATISTICS",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-statistics.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_ANKUS_CERTAIN_FACTOR_SUM",
                    "name": "Certainty Factor based Sum",
                    "qualifierLabel": "acfs",
                    "description": "Certainty Factor based Sum",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "ETL",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-etl.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_ANKUS_NORMAL",
                    "name": "Min/Max Normalization",
                    "qualifierLabel": "anormal",
                    "description": "Min/Max Normalization",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "ETL",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-etl.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ETL_CHAR_REMOVER",
                    "name": "Remove Characters",
                    "qualifierLabel": "remove_chars",
                    "description": "Remove Characters",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "ETL",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-etl.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ETL_ACCOUNTING",
                    "name": "Accounting ETL",
                    "qualifierLabel": "etl_accounting",
                    "description": "Accounting ETL",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "ETL",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-etl.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ETL_AGGREGATE",
                    "name": "Aggregate ETL",
                    "qualifierLabel": "etl_aggregate",
                    "description": "Aggregate ETL",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "ETL",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-etl.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ETL_APACHE_ACCESS",
                    "name": "Apache Access To CSV",
                    "qualifierLabel": "apache_access",
                    "description": "Apache Access To CSV",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "ETL",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-etl.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ETL_CLEAN",
                    "name": "Clean ETL",
                    "qualifierLabel": "etl_clean",
                    "description": "Clean ETL",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "ETL",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-etl.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ETL_FILTER",
                    "name": "Filter ETL",
                    "qualifierLabel": "etl_filter",
                    "description": "Filter ETL",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "ETL",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-etl.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ETL_GENERATE",
                    "name": "Generate ETL",
                    "qualifierLabel": "etl_generate",
                    "description": "Generate ETL",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "ETL",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-etl.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ETL_GREP",
                    "name": "Grep ETL",
                    "qualifierLabel": "etl_grep",
                    "description": "Grep ETL",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "ETL",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-etl.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ETL_GROUPBY",
                    "name": "Group by ETL",
                    "qualifierLabel": "etl_groupby",
                    "description": "Group by ETL",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "ETL",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-etl.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ETL_RANK",
                    "name": "Rank ETL",
                    "qualifierLabel": "etl_rank",
                    "description": "Rank ETL",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "ETL",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-etl.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ETL_REPLACE_COLUMN",
                    "name": "Replace Column ETL",
                    "qualifierLabel": "etl_replace_column",
                    "description": "Replace Column ETL",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "ETL",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-etl.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ETL_REPLACE_DELIMITER",
                    "name": "Replace Delimiter ETL",
                    "qualifierLabel": "etl_replace_delimiter",
                    "description": "Replace Delimiter ETL",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "ETL",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-etl.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ETL_TEXT_TO_SEQ",
                    "name": "Text to sequence ETL",
                    "qualifierLabel": "etl_text_to_seq",
                    "description": "Text to sequence ETL",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "RULES",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-etl.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "MVEL_EDITOR",
                    "name": "Expression (Editor)",
                    "qualifierLabel": "mvel_editor",
                    "description": "Expression MVEL",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "RULES",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-etl.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "MVEL_FILE",
                    "name": "Expression (File)",
                    "qualifierLabel": "mvel_file",
                    "description": "Expression MVEL",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "RULES",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-etl.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "DROOLS_EDITOR",
                    "name": "Drools Rule (Editor)",
                    "qualifierLabel": "drools_editor",
                    "description": "Drools Rule",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "RULES",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-etl.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "DROOLS_FILE",
                    "name": "Drools Rule (File)",
                    "qualifierLabel": "drools_file",
                    "description": "Drools Rule",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "RULES",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-etl.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ESPER_EDITOR",
                    "name": "CEP Esper (Editor)",
                    "qualifierLabel": "esper_editor",
                    "description": "CEP Esper",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "RULES",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-etl.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ESPER_FILE",
                    "name": "CEP Esper (File)",
                    "qualifierLabel": "esper_file",
                    "description": "CEP Esper",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                /*{
                    "type": "ETL",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-etl.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ETL_UIMA_SEQ",
                    "name": "UIMA To Sequence File",
                    "qualifierLabel": "uima_seq",
                    "description": "UIMA To Sequence File",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "ETL",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-etl.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ETL_UIMA_APP",
                    "name": "UIMA Application",
                    "qualifierLabel": "uima_app",
                    "description": "UIMA Application",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },*/
                {
                    "type": "MINING",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mining.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_ANKUS_CORR_BOOL",
                    "name": "Boolean Similarity/Correlation",
                    "qualifierLabel": "acorrb",
                    "description": "Boolean Similarity/Correlation",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MINING",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mining.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_ANKUS_CORR_NUMERIC",
                    "name": "Numeric Similarity/Correlation",
                    "qualifierLabel": "acorrn",
                    "description": "Numeric Similarity/Correlation",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MINING",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mining.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_ANKUS_CORR_STRING",
                    "name": "String Similarity",
                    "qualifierLabel": "acorrs",
                    "description": "String Similarity",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MINING",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mining.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_ANKUS_ID3",
                    "name": "ID3 Classification",
                    "qualifierLabel": "aid3",
                    "description": "ID3 Classification",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },

                {
                    "type": "MINING",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mining.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_ANKUS_KMEANS",
                    "name": "K-Means Clustering",
                    "qualifierLabel": "akmeans",
                    "description": "K-Means based Clustering",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MINING",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mining.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_ANKUS_EM",
                    "name": "EM Clustering",
                    "qualifierLabel": "aem",
                    "description": "EM based Clustering",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MINING",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mining.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_ANKUS_CF_SIM",
                    "name": "CF based Similarity",
                    "qualifierLabel": "acfsim",
                    "description": "Collaborative Filtering based Similarity",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MINING",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mining.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_ANKUS_CONTENT_SIM",
                    "name": "Content based Similarity",
                    "qualifierLabel": "aconsim",
                    "description": "Content based Similarity",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MINING",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mining.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_ANKUS_CF_USER_RECOMMEND",
                    "name": "User Similarity based Recommendation",
                    "qualifierLabel": "auserrec",
                    "description": "Collaborative Filtering User based Recommendation",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MINING",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mining.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_ANKUS_CF_ITEM_RECOMMEND",
                    "name": "Item Similarity based Recommendation",
                    "qualifierLabel": "aitemrec",
                    "description": "Collaborative Filtering Item based Recommendation",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MAHOUT",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mahout.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_MAHOUT_CF_ITEM",
                    "name": "Item-Based Collaborative Filtering",
                    "qualifierLabel": "mahoutitemrec",
                    "description": "Item-Based Collaborative Filtering",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MAHOUT",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mahout.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_MAHOUT_MATRIX_FACT_ALS",
                    "name": "Factorized Recommendation",
                    "qualifierLabel": "mahoutmatrixfact",
                    "description": "Factorized Recommendation",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MAHOUT",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mahout.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_MAHOUT_PARALLEL_ALS",
                    "name": "Parallel ALS",
                    "qualifierLabel": "mahoutparallelals",
                    "description": "Parallel ALS",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MAHOUT",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mahout.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_MAHOUT_KMEANS",
                    "name": "k-Means Clustering",
                    "qualifierLabel": "mahoutkmeans",
                    "description": "k-Means Clustering",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MAHOUT",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mahout.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_MAHOUT_FUZZY_K_MEANS",
                    "name": "Fuzzy k-Means Clustering",
                    "qualifierLabel": "mahoutfuzzykmeans",
                    "description": "Fuzzy k-Means Clustering",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MAHOUT",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mahout.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_MAHOUT_STREAMING_K_MEANS",
                    "name": "Streaming k-Means Clustering",
                    "qualifierLabel": "mahoutstreamingkmeans",
                    "description": "Streaming k-Means Clustering",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MAHOUT",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mahout.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_MAHOUT_QUALCLUSTER",
                    "name": "Cluster Quality Summarizer",
                    "qualifierLabel": "Mahout Cluster Quality Summarizer",
                    "description": "Mahout Cluster Quality Summarizer",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MAHOUT",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mahout.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_MAHOUT_SEQ2SPARSE",
                    "name": "Sequence File To Sparse Vector",
                    "qualifierLabel": "mahoutseq2sparse",
                    "description": "Sequence File to Sparse Vector",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MAHOUT",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mahout.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_MAHOUT_SPECTRAL_K_MEANS",
                    "name": "Spectral k-Means Clustering",
                    "qualifierLabel": "mahoutspectralkmeans",
                    "description": "Spectral k-Means Clustering",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MAHOUT",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mahout.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_MAHOUT_CLUSTER_DUMP",
                    "name": "Cluster Dump",
                    "qualifierLabel": "mahout cluser dump",
                    "description": "Cluster Dump",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MAHOUT",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mahout.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_MAHOUT_SEQDIRECTORY",
                    "name": "To Sequence File",
                    "qualifierLabel": "Mahout Seqdirectory",
                    "description": "To Sequence File",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MAHOUT",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mahout.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_MAHOUT_TRAINNB",
                    "name": "Train Naive Bayes / CNaive Bayes",
                    "qualifierLabel": "mahouttrainnb",
                    "description": "Train Naive Bayes / CNaive Bayes",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MAHOUT",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mahout.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_MAHOUT_TESTNB",
                    "name": "Test Naive Bayes / CNaive Bayes",
                    "qualifierLabel": "mahouttestnb",
                    "description": "Test Naive Bayes / CNaive Bayes",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "GIS",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-gis.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "DBF_TO_CSV",
                    "name": "DBF To CSV",
                    "qualifierLabel": "dbfToCsv",
                    "description": "DBF To CSV",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "GIS",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-gis.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ExtractLink",
                    "name": "Extract Link ID From GPS",
                    "qualifierLabel": "extractLink",
                    "description": "Extract Link ID From GPS",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                }
            ]
        }
    }
});